
###############################
# API doc
###############################

build_api_doc:
  stage: build
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - mkdir build
    - cd build
    - conan install ..
    - cmake -DBUILD_DOCS=ON ..
    - make CMakeApiDoc
    - make CppApiDoc
  artifacts:
    expire_in: 1 day
    paths:
      - build

pages:
  stage: deploy
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-minimal:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  dependencies:
    - build_api_doc
  script:
    - mkdir public
    - mv build/doc/cmake-api/html public/cmake-api
    - mv build/doc/cpp-api/html public/cpp-api
  artifacts:
    paths:
      - public
