
# TODO: remove templates etc..
include:
  - local: 'ci_cd/GitLab/Doc.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Linux.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Windows.yml'
  - local: 'ci_cd/GitLab/Common.yml'
  - local: 'ci_cd/GitLab/Conan_Templates.yml'
  - local: 'ci_cd/GitLab/BuildAndTest_Templates.yml'


###############################
# Reusable templates
###############################


.conan_create_deployutils:
  stage: build
  script:
    - !reference [.setup_conan, script]
    - conan create packaging/conan/MdtDeployUtils 0.0.0@scandyna/testing --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE

.conan_create_deployutils_core:
  stage: build
  script:
    - !reference [.setup_conan, script]
    - conan create packaging/conan/MdtDeployUtilsCore 0.0.0@scandyna/testing --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE


.deploy_base:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never

.deploy_apps:
  extends: .deploy_base
  script:
    - !reference [.setup_conan, script]
    - conan create packaging/conan/MdtDeployUtils scandyna/testing --profile $CONAN_PROFILE -s build_type=Release
    - conan user --password ${CI_JOB_TOKEN} --remote scandyna ci_user
    - conan upload MdtDeployUtils/* --remote scandyna --all -c

.deploy_libs:
  extends: .deploy_base
  script:
    - !reference [.setup_conan, script]
    - conan create packaging/conan/MdtDeployUtilsCore scandyna/testing --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE
    - conan user --password ${CI_JOB_TOKEN} --remote scandyna ci_user
    - conan upload MdtDeployUtilsCore/* --remote scandyna --all -c


###############################
# Linux
###############################



.deploy_linux_libs:
  image: registry.gitlab.com/scandyna/docker-images-ubuntu/ubuntu-18.04-cpp-gui:latest
  extends: .deploy_libs



conan_deployutils_linux_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-ubuntu/ubuntu-18.04-cpp:latest
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  extends: .conan_create_deployutils


conan_deployutils_core_linux_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-ubuntu/ubuntu-18.04-cpp:latest
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  extends: .conan_create_deployutils_core



deploy_linux_apps:
  image: registry.gitlab.com/scandyna/docker-images-ubuntu/ubuntu-18.04-cpp-gui:latest
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
  extends: .deploy_apps

deploy_linux_libs_gcc7_x86_64_debug:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  extends: .deploy_linux_libs

deploy_linux_libs_gcc7_x86_64_release:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Release
  extends: .deploy_linux_libs

deploy_linux_libs_gcc7_x86_64_relwithdebinfo:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: RelWithDebInfo
  extends: .deploy_linux_libs


###############################
# Windows
###############################


.conan_create_deployutils_windows:
  extends:
    - .conan_create_deployutils
    - .windows_runner
  before_script:
    - $env:PATH += ";$QT_PREFIX_PATH;$BOOST_PREFIX_PATH"

.conan_create_deployutils_core_windows:
  extends:
    - .conan_create_deployutils_core
    - .windows_runner
  before_script:
    - $env:PATH += ";$QT_PREFIX_PATH;$BOOST_PREFIX_PATH"


.deploy_windows_libs:
  extends:
    - .deploy_libs
    - .windows_runner
  before_script:
    - $env:PATH += ";$QT_PREFIX_PATH;$BOOST_PREFIX_PATH"



#build_windows_gcc7_x86_32_debug:
  #image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win32_mingw73:latest
  #variables:
    #CONAN_PROFILE: windows_gcc7_x86
    #BUILD_TYPE: Debug
    #CMAKE_GENERATOR: "MinGW Makefiles"
    #BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    #QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  #extends: .build_windows

#test_windows_gcc7_x86_32_debug:
  #image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win32_mingw73:latest
  #variables:
    #CONAN_PROFILE: windows_gcc7_x86
    #BUILD_TYPE: Debug
  #dependencies:
    #- build_windows_gcc7_x86_32_debug
  #extends: .test_windows



conan_deployutils_windows_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
    CONAN_CMAKE_GENERATOR: "MinGW Makefiles"
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .conan_create_deployutils_windows

conan_deployutils_windows_msvc16_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .conan_create_deployutils_windows


conan_deployutils_core_windows_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
    CONAN_CMAKE_GENERATOR: "MinGW Makefiles"
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .conan_create_deployutils_core_windows

conan_deployutils_core_windows_msvc16_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .conan_create_deployutils_core_windows


deploy_windows_apps:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  extends:
    - .deploy_apps
    - .windows_runner
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  before_script:
    - $env:PATH += ";$QT_PREFIX_PATH;$BOOST_PREFIX_PATH"

deploy_windows_libs_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_libs

deploy_windows_libs_gcc7_x86_64_release:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Release
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_libs

deploy_windows_libs_gcc7_x86_64_relwithdebinfo:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: RelWithDebInfo
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_libs


#deploy_windows_gcc7_x86_32_debug:
  #image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win32_mingw73:latest
  #variables:
    #CONAN_PROFILE: windows_gcc7_x86
    #BUILD_TYPE: Debug
    #BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    #QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  #extends: .deploy_windows_conan

#deploy_windows_gcc7_x86_32_release:
  #image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win32_mingw73:latest
  #variables:
    #CONAN_PROFILE: windows_gcc7_x86
    #BUILD_TYPE: Release
    #BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    #QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  #extends: .deploy_windows_conan

#deploy_windows_gcc7_x86_32_relwithdebinfo:
  #image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win32_mingw73:latest
  #variables:
    #CONAN_PROFILE: windows_gcc7_x86
    #BUILD_TYPE: RelWithDebInfo
    #BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    #QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  #extends: .deploy_windows_conan


deploy_windows_libs_msvc_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .deploy_windows_libs

deploy_windows_libs_msvc_x86_64_release:
  image: registry.gitlab.com/scandyna/docker-images-windows/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Release
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .deploy_windows_libs
