
###############################
# Runners + global parts
###############################

# GitLab shared new Windows runners
# They currently not support Docker engine
#.windows_runner:
  #tags:
    #- shared-windows
    #- windows
    #- windows-1809

.windows_runner:
  tags:
    - docker-windows

stages:
  - build
  - test
  - deploy

###############################
# Reusable templates
###############################

# Uncomment the conan upload line for real deployment
.deploy_conan:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
    - conan user -p $BINTRAY_API_KEY -r scandyna scandyna
    - conan create . scandyna/testing --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE $CONAN_EXTRA_ARGUMENTS
    - conan upload _Project_name_/* --remote scandyna --all -c

###############################
# Linux
###############################

.build_linux:
  stage: build
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest
  before_script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
  script:
    - mkdir build
    - cd build
    - conan install --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE $CONAN_EXTRA_ARGUMENTS ..
    - source activate.sh
    - cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DWARNING_AS_ERROR=ON -DBUILD_TESTS=ON -DBUILD_USE_IPO_LTO=$BUILD_USE_IPO_LTO ..
    - make -j4
    - source deactivate.sh
  artifacts:
    expire_in: 1 day
    paths:
      - build


# Here we have to get the binaries got with conan during build
.test_linux:
  stage: test
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest
  before_script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
  script:
    - cd build
    - conan install --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE $CONAN_EXTRA_ARGUMENTS ..
    - ctest --output-on-failure .

.deploy_linux_conan:
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp-gui:latest
  extends: .deploy_conan


build_linux_gcc7_x86_64_debug:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  extends: .build_linux

test_linux_gcc7_x86_64_debug:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  dependencies:
    - build_linux_gcc7_x86_64_debug
  extends: .test_linux


build_linux_gcc7_x86_64_release:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Release
    BUILD_USE_IPO_LTO: "ON"
  extends: .build_linux

test_linux_gcc7_x86_64_release:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Release
  dependencies:
    - build_linux_gcc7_x86_64_release
  extends: .test_linux


# Currently, we have no pre-built Conan package for Qt with Widgets
build_linux_clang6.0_x86_64_libc++_release:
  variables:
    CONAN_PROFILE: linux_clang6.0_x86_64_libc++_qt_gui_modules
    BUILD_TYPE: Release
    BUILD_USE_IPO_LTO: "ON"
    CONAN_EXTRA_ARGUMENTS: -o MdtApplication:use_conan_qt=True -o use_conan_qt=True
  extends: .build_linux

test_linux_clang6.0_x86_64_libc++_release:
  variables:
    CONAN_PROFILE: linux_clang6.0_x86_64_libc++_qt_gui_modules
    BUILD_TYPE: Release
    CONAN_EXTRA_ARGUMENTS: -o MdtApplication:use_conan_qt=True -o use_conan_qt=True
  dependencies:
    - build_linux_clang6.0_x86_64_libc++_release
  extends: .test_linux


deploy_linux_gcc7_x86_64_debug:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Debug
  extends: .deploy_linux_conan

deploy_linux_gcc7_x86_64_release:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: Release
  extends: .deploy_linux_conan

deploy_linux_gcc7_x86_64_relwithdebinfo:
  variables:
    CONAN_PROFILE: linux_gcc7_x86_64
    BUILD_TYPE: RelWithDebInfo
  extends: .deploy_linux_conan


deploy_linux_clang6.0_x86_64_libc++_debug:
  variables:
    CONAN_PROFILE: linux_clang6.0_x86_64_libc++_qt_gui_modules
    CONAN_EXTRA_ARGUMENTS: -o _Project_name_:use_conan_qt=True
    BUILD_TYPE: Debug
  extends: .deploy_linux_conan

deploy_linux_clang6.0_x86_64_libc++_release:
  variables:
    CONAN_PROFILE: linux_clang6.0_x86_64_libc++_qt_gui_modules
    CONAN_EXTRA_ARGUMENTS: -o _Project_name_:use_conan_qt=True
    BUILD_TYPE: Release
  extends: .deploy_linux_conan

deploy_linux_clang6.0_x86_64_libc++_relwithdebinfo:
  variables:
    CONAN_PROFILE: linux_clang6.0_x86_64_libc++_qt_gui_modules
    CONAN_EXTRA_ARGUMENTS: -o _Project_name_:use_conan_qt=True
    BUILD_TYPE: RelWithDebInfo
  extends: .deploy_linux_conan

###############################
# Windows
###############################

.build_windows:
  stage: build
  extends:
    - .windows_runner
  before_script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
  script:
    - mkdir build
    - cd build
    - conan install --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE $CONAN_EXTRA_ARGUMENTS ..
    - ./activate
    - cmake -G"$CMAKE_GENERATOR" $CMAKE_GENERATOR_EXTRA_ARGS -DCMAKE_BUILD_TYPE=$BUILD_TYPE
            -DCMAKE_PREFIX_PATH="$BOOST_PREFIX_PATH;$QT_PREFIX_PATH"
            -DWARNING_AS_ERROR=ON -DBUILD_TESTS=ON ..
    - cmake --build . --config $BUILD_TYPE -j4
    - ./deactivate
  artifacts:
    expire_in: 1 day
    paths:
      - build

# Here we have to get the binaries got with conan during build
.test_windows:
  stage: test
  extends:
    - .windows_runner
  before_script:
    - conan config install --source-folder conan https://gitlab.com/scandyna/conan-config.git
    - conan remote update scandyna https://api.bintray.com/conan/scandyna/public-conan --insert 0 # Check for package in scandyna first
  script:
    - cd build
    - conan install --profile $CONAN_PROFILE -s build_type=$BUILD_TYPE $CONAN_EXTRA_ARGUMENTS ..
    - ctest --output-on-failure --build-config $BUILD_TYPE .

.deploy_windows_conan:
  extends:
    - .deploy_conan
    - .windows_runner
  before_script:
    - $env:PATH += ";$QT_PREFIX_PATH;$BOOST_PREFIX_PATH"


build_windows_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
    CMAKE_GENERATOR: "MinGW Makefiles"
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .build_windows

test_windows_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
  dependencies:
    - build_windows_gcc7_x86_64_debug
  extends: .test_windows


build_windows_gcc7_x86_32_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win32_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86
    BUILD_TYPE: Debug
    CMAKE_GENERATOR: "MinGW Makefiles"
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  extends: .build_windows

test_windows_gcc7_x86_32_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win32_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86
    BUILD_TYPE: Debug
  dependencies:
    - build_windows_gcc7_x86_32_debug
  extends: .test_windows


build_windows_msvc16_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
    CMAKE_GENERATOR: "Visual Studio 16 2019"
    CMAKE_GENERATOR_EXTRA_ARGS: -Ax64
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .build_windows

test_windows_msvc16_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
  dependencies:
    - build_windows_msvc16_x86_64_debug
  extends: .test_windows


deploy_windows_gcc7_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_conan

deploy_windows_gcc7_x86_64_release:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: Release
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_conan

deploy_windows_gcc7_x86_64_relwithdebinfo:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86_64
    BUILD_TYPE: RelWithDebInfo
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_64"
  extends: .deploy_windows_conan


deploy_windows_gcc7_x86_32_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win32_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  extends: .deploy_windows_conan

deploy_windows_gcc7_x86_32_release:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win32_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86
    BUILD_TYPE: Release
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  extends: .deploy_windows_conan

deploy_windows_gcc7_x86_32_relwithdebinfo:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win32_mingw73:latest
  variables:
    CONAN_PROFILE: windows_gcc7_x86
    BUILD_TYPE: RelWithDebInfo
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/mingw73_32"
  extends: .deploy_windows_conan


deploy_windows_msvc_x86_64_debug:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Debug
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .deploy_windows_conan

deploy_windows_msvc_x86_64_release:
  image: registry.gitlab.com/scandyna/docker-images/windows-cpp-qt-5.14.2-win64_msvc2017_64:latest
  variables:
    CONAN_PROFILE: windows_msvc16_x86_64
    BUILD_TYPE: Release
    BOOST_PREFIX_PATH: "C:/Libraries/boost_1_73_0"
    QT_PREFIX_PATH: "C:/Qt/5.14.2/msvc2017_64"
  extends: .deploy_windows_conan

###############################
# API doc
###############################

build_api_doc:
  stage: build
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-cpp:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  script:
    - mkdir build
    - cd build
    - conan install ..
    - cmake -DBUILD_DOCS=ON ..
    - make CMakeApiDoc
    - make CppApiDoc
  artifacts:
    expire_in: 1 day
    paths:
      - build

pages:
  stage: deploy
  image: registry.gitlab.com/scandyna/docker-images/ubuntu-18.04-minimal:latest
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: never
  dependencies:
    - build_api_doc
  script:
    - mkdir public
    - mv build/doc/cmake-api/html public/cmake-api
    - mv build/doc/cpp-api/html public/cpp-api
  artifacts:
    paths:
      - public
